"""Script to write the full llm_registry.py with litellm as universal provider."""
import pathlib

lines = []
lines.append('"""LLM provider registry — auto-selects provider from model name or env var.')
lines.append('')
lines.append('Supports:')
lines.append('  - litellm: Universal proxy for ALL providers (Gemini, OpenAI, Ollama, etc.)')
lines.append('  - openai: Direct OpenAI SDK or any OpenAI-compatible endpoint (Ollama, vLLM)')
lines.append('  - google-adk: Google Gemini via ADK SDK')
lines.append('"""')
lines.append('')
lines.append('from __future__ import annotations')
lines.append('')
lines.append('import os')
lines.append('from typing import Any, Dict, Optional, Type')
lines.append('')
lines.append('from backend.agents.runtime.llm_runtime import LLMRuntime')
lines.append('from backend.common.logger import logger')
lines.append('')
lines.append('# Provider registry — populated at import time')
lines.append('_PROVIDERS: Dict[str, Type[LLMRuntime]] = {}')
lines.append('')
lines.append('')
lines.append('def register_provider(name: str, runtime_class: Type[LLMRuntime]) -> None:')
lines.append('    """Register an LLM provider by name."""')
lines.append('    _PROVIDERS[name.lower()] = runtime_class')
lines.append('    logger.info(f"LLMRegistry: registered provider \'{name}\' -> {runtime_class.__name__}")')
lines.append('')
lines.append('')
lines.append('def get_provider(model: Optional[str] = None, provider: Optional[str] = None) -> Type[LLMRuntime]:')
lines.append('    """Get the LLM provider class for the given model or explicit provider.')
lines.append('')
lines.append('    Selection priority:')
lines.append('    1. Explicit `provider` argument')
lines.append('    2. LLM_PROVIDER env var')
lines.append('    3. Auto-detect from model name pattern')
lines.append('    4. Fallback to first registered provider')
lines.append('    """')
lines.append('    # 1. Explicit provider')
lines.append('    if provider:')
lines.append('        cls = _PROVIDERS.get(provider.lower())')
lines.append('        if cls:')
lines.append('            return cls')
lines.append('        raise ValueError(')
lines.append('            f"Unknown LLM provider: \'{provider}\'. "')
lines.append('            f"Available: {list(_PROVIDERS.keys())}"')
lines.append('        )')
lines.append('')
lines.append('    # 2. Environment variable')
lines.append('    env_provider = os.environ.get("LLM_PROVIDER", "").lower()')
lines.append('    if env_provider:')
lines.append('        cls = _PROVIDERS.get(env_provider)')
lines.append('        if cls:')
lines.append('            return cls')
lines.append('        logger.warning(')
lines.append('            f"LLMRegistry: unknown LLM_PROVIDER=\'{env_provider}\', "')
lines.append('            f"falling back to auto-detect"')
lines.append('        )')
lines.append('')
lines.append('    # 3. Auto-detect from model name')
lines.append('    if model:')
lines.append('        model_lower = model.lower()')
lines.append('        if "gemini" in model_lower:')
lines.append('            # Try litellm first (handles gemini via API key), then google-adk')
lines.append('            for p in ["litellm", "google-adk", "openai"]:')
lines.append('                cls = _PROVIDERS.get(p)')
lines.append('                if cls:')
lines.append('                    return cls')
lines.append('        if any(x in model_lower for x in ("gpt-", "o1", "o3", "claude", "gpt-5")):')
lines.append('            for p in ["openai", "litellm"]:')
lines.append('                cls = _PROVIDERS.get(p)')
lines.append('                if cls:')
lines.append('                    return cls')
lines.append('        # Ollama models: llama, qwen, gemma, phi, mistral, etc.')
lines.append('        if any(x in model_lower for x in ("llama", "qwen", "mistral", "phi", "deepseek", "gemma", ":")):')
lines.append('            for p in ["litellm", "openai"]:')
lines.append('                cls = _PROVIDERS.get(p)')
lines.append('                if cls:')
lines.append('                    return cls')
lines.append('')
lines.append('    # 4. Fallback to first registered provider')
lines.append('    if _PROVIDERS:')
lines.append('        first_name = next(iter(_PROVIDERS))')
lines.append('        return _PROVIDERS[first_name]')
lines.append('')
lines.append('    raise RuntimeError(')
lines.append('        "No LLM providers registered. Install at least one of: "')
lines.append('        "litellm, openai, google-adk"')
lines.append('    )')
lines.append('')
lines.append('')
lines.append('def create_llm_runtime(')
lines.append('    *,')
lines.append('    model: Optional[str] = None,')
lines.append('    provider: Optional[str] = None,')
lines.append('    **kwargs: Any,')
lines.append(') -> LLMRuntime:')
lines.append('    """Create an LLM runtime instance with auto-detected provider.')
lines.append('')
lines.append('    Args:')
lines.append('        model: Model name (e.g., gemini-3.1-flash-lite-preview, gpt-5.4, llama3.2)')
lines.append('        provider: Explicit provider name (litellm, openai, google-adk)')
lines.append('        **kwargs: Additional runtime config (timeout, temperature, etc.)')
lines.append('')
lines.append('    Returns:')
lines.append('        Configured LLMRuntime instance')
lines.append('    """')
lines.append('    from backend.config.agent_model import AGENT_MODEL')
lines.append('')
lines.append('    resolved_model = model or AGENT_MODEL')
lines.append('    provider_class = get_provider(model=resolved_model, provider=provider)')
lines.append('    return provider_class(model=resolved_model, **kwargs)')
lines.append('')
lines.append('')
lines.append('def _register_builtin_providers() -> None:')
lines.append('    """Register built-in LLM providers based on installed packages."""')
lines.append('    # Priority 1: litellm (universal proxy for ALL providers)')
lines.append('    try:')
lines.append('        import litellm  # noqa: F401')
lines.append('        from backend.agents.runtime.litellm_runtime import LiteLLMRuntime')
lines.append('        register_provider("litellm", LiteLLMRuntime)')
lines.append('    except ImportError:')
lines.append('        pass')
lines.append('')
lines.append('    # Priority 2: openai (direct or Ollama-compatible)')
lines.append('    try:')
lines.append('        import openai  # noqa: F401')
lines.append('        from backend.agents.runtime.openai_runtime import OpenAIRuntime')
lines.append('        register_provider("openai", OpenAIRuntime)')
lines.append('    except ImportError:')
lines.append('        pass')
lines.append('')
lines.append('    # Priority 3: google-adk (Gemini via ADK SDK)')
lines.append('    try:')
lines.append('        import google_adk  # noqa: F401')
lines.append('        from backend.agents.runtime.google_adk_runtime import GoogleADKRuntime')
lines.append('        register_provider("google-adk", GoogleADKRuntime)')
lines.append('    except ImportError:')
lines.append('        pass')
lines.append('')
lines.append('')
lines.append('_register_builtin_providers()')

pathlib.Path('backend/agents/runtime/llm_registry.py').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'Wrote {len(lines)} lines to llm_registry.py')
