"""Agent runtime scaffolding for the agentic backend_retiring."""

from .agent_registry import (
    AgentDescriptor,
    AgentRegistry,
    DEFAULT_AGENT_DESCRIPTORS,
    DEFAULT_AGENT_REGISTRY,
    get_default_agent_registry,
)
from .base import AgentRunContext, AgentRunError, AgentRunResult, BaseAgent, FirmDepartmentAgent
from .compliance_agent import COMPLIANCE_AGENT_INSTRUCTION, ComplianceAgentWrapper
from .correlation_agent import CORRELATION_AGENT_INSTRUCTION, CorrelationAgentWrapper
from .drawdown_agent import DRAWDOWN_AGENT_INSTRUCTION, DrawdownAgentWrapper
from .execution_agent import EXECUTION_AGENT_INSTRUCTION, ExecutionAgentWrapper
from .exposure_agent import EXPOSURE_AGENT_INSTRUCTION, ExposureAgentWrapper
from .intent_router import IntentRouterAgent, IntentRouterError, intent_router_agent
from .portfolio_agent import PORTFOLIO_AGENT_INSTRUCTION, PortfolioAgentWrapper
from .permissions import (
    AgentToolPermissionDecision,
    AgentToolPermissionError,
    AgentToolPermissionService,
    DEFAULT_AGENT_TOOL_ALLOWLIST,
    get_default_permission_service,
)
from .orchestrator import AgentControlPlaneOrchestrator, AgentControlPlaneResult, DefaultFirmPlanner
from .research.market_intelligence_agent import MarketIntelligenceAgent
from .research.strategy_scout_agent import StrategyScoutAgent
from .research.technical_analyst_agent import TechnicalAnalystAgent
from .task_manager import (
    AgentTaskManager,
    AgentTaskTransitionError,
    TaskTreeNode,
    VALID_TASK_TRANSITIONS,
)
from .refine_agent import REFINE_AGENT_INSTRUCTION, RefineAgentWrapper
from .risk_governor_agent import RiskGovernorAgentAdapter
from .route_decision import RouteDecision, RouteDecisionService
from .monitoring_agent import MONITORING_AGENT_INSTRUCTION, MonitoringAgentWrapper
from .orchestrator_agent import ORCHESTRATOR_AGENT_INSTRUCTION, OrchestratorAgentWrapper
from .research_agent import RESEARCH_AGENT_INSTRUCTION, ResearchAgentWrapper
from .regime_agent import REGIME_AGENT_INSTRUCTION, RegimeAgentWrapper
from .strategy_agent import STRATEGY_AGENT_INSTRUCTION, StrategyAgentWrapper
from .strategy_creator_agent import (
    STRATEGY_CREATOR_AGENT_INSTRUCTION,
    StrategyCreatorAgent,
    StrategyCreatorResult,
)
from .slippage_agent import SLIPPAGE_AGENT_INSTRUCTION, SlippageAgentWrapper
from .volatility_agent import VOLATILITY_AGENT_INSTRUCTION, VolatilityAgentWrapper
from .runtime import (
    ADKRunRequest,
    ADKRunResult,
    ADKRunnerConfig,
    ADKRunnerService,
    AgentSession,
    AgentExecutionContext,
    AgentExecutionResult,
    AgentRuntime,
    CanonicalOutputValidator,
    CanonicalValidationResult,
    ContractValidationError,
    EvaluatorRubric,
    EvaluatorRubricCriterion,
    RefinementRecommendation,
    ResearchAssertionCheck,
    TrajectoryEvaluation,
    TrajectoryEvaluationService,
    ContextRedactionMiddleware,
    detect_unsupported_assertions,
    generate_refinement_recommendations,
    hash_schema_name,
    PromptProvenance,
    PromptRegistryService,
    PromptRegistryRecord,
    PromptResolutionError,
    PromptStatus,
    PromptEvalCase,
    PromptEvalCaseResult,
    PromptEvalHarness,
    PromptEvalReport,
    WorkflowPatternRegistration,
    WorkflowPatternRegistry,
    load_prompt_eval_cases,
    RuntimeTrajectoryLog,
    RuntimeTrajectoryLogService,
    build_run_trajectory_log,
    RedactedContext,
    attach_prompt_provenance,
    attach_prompt_provenance_to_run_result,
    build_prompt_provenance,
    SessionManager,
    SessionState,
    ToolAllowlistDecision,
    ToolAllowlistMiddleware,
    ToolPolicyError,
    EvaluatorOptimizerResult,
    EvaluatorOptimizerStep,
    EvaluatorOptimizerWorkflowRunner,
    OrchestratorWorkerTask,
    OrchestratorWorkerWorkflowRunner,
    ParallelAggregateResult,
    ParallelWorkflowRunner,
    ParallelWorkflowTask,
    RefineLoopGuardDecision,
    SequentialWorkflowRunner,
    SequentialWorkflowStep,
    RoutingWorkflowBranch,
    RoutingWorkflowRunner,
    WorkerGroupResult,
    enforce_refine_loop_limit,
    WorkflowMemoryBinding,
    WorkflowMemoryBindings,
)

__all__ = [
    "ADKRunRequest",
    "ADKRunResult",
    "ADKRunnerConfig",
    "ADKRunnerService",
    "AgentControlPlaneOrchestrator",
    "AgentControlPlaneResult",
    "AgentDescriptor",
    "AgentRegistry",
    "AgentRunContext",
    "AgentRunError",
    "AgentRunResult",
    "COMPLIANCE_AGENT_INSTRUCTION",
    "CORRELATION_AGENT_INSTRUCTION",
    "DRAWDOWN_AGENT_INSTRUCTION",
    "EXECUTION_AGENT_INSTRUCTION",
    "EXPOSURE_AGENT_INSTRUCTION",
    "REFINE_AGENT_INSTRUCTION",
    "MONITORING_AGENT_INSTRUCTION",
    "ORCHESTRATOR_AGENT_INSTRUCTION",
    "PORTFOLIO_AGENT_INSTRUCTION",
    "RESEARCH_AGENT_INSTRUCTION",
    "REGIME_AGENT_INSTRUCTION",
    "SLIPPAGE_AGENT_INSTRUCTION",
    "STRATEGY_AGENT_INSTRUCTION",
    "STRATEGY_CREATOR_AGENT_INSTRUCTION",
    "VOLATILITY_AGENT_INSTRUCTION",
    "AgentSession",
    "AgentTaskManager",
    "AgentTaskTransitionError",
    "AgentToolPermissionDecision",
    "AgentToolPermissionError",
    "AgentToolPermissionService",
    "AgentExecutionContext",
    "AgentExecutionResult",
    "AgentRuntime",
    "BaseAgent",
    "ComplianceAgentWrapper",
    "CorrelationAgentWrapper",
    "DrawdownAgentWrapper",
    "ExecutionAgentWrapper",
    "ExposureAgentWrapper",
    "IntentRouterAgent",
    "IntentRouterError",
    "MonitoringAgentWrapper",
    "MarketIntelligenceAgent",
    "OrchestratorAgentWrapper",
    "PortfolioAgentWrapper",
    "RefineAgentWrapper",
    "RiskGovernorAgentAdapter",
    "RouteDecision",
    "RouteDecisionService",
    "ResearchAgentWrapper",
    "RegimeAgentWrapper",
    "SlippageAgentWrapper",
    "StrategyAgentWrapper",
    "StrategyCreatorAgent",
    "StrategyCreatorResult",
    "StrategyScoutAgent",
    "TechnicalAnalystAgent",
    "VolatilityAgentWrapper",
    "EvaluatorRubric",
    "EvaluatorRubricCriterion",
    "RefinementRecommendation",
    "ResearchAssertionCheck",
    "TrajectoryEvaluation",
    "TrajectoryEvaluationService",
    "CanonicalOutputValidator",
    "CanonicalValidationResult",
    "ContractValidationError",
    "detect_unsupported_assertions",
    "generate_refinement_recommendations",
    "hash_schema_name",
    "ContextRedactionMiddleware",
    "DEFAULT_AGENT_TOOL_ALLOWLIST",
    "DEFAULT_AGENT_DESCRIPTORS",
    "DEFAULT_AGENT_REGISTRY",
    "DefaultFirmPlanner",
    "FirmDepartmentAgent",
    "PromptProvenance",
    "PromptRegistryService",
    "PromptRegistryRecord",
    "PromptResolutionError",
    "PromptStatus",
    "PromptEvalCase",
    "PromptEvalCaseResult",
    "PromptEvalHarness",
    "PromptEvalReport",
    "WorkflowPatternRegistration",
    "WorkflowPatternRegistry",
    "load_prompt_eval_cases",
    "RuntimeTrajectoryLog",
    "RuntimeTrajectoryLogService",
    "build_run_trajectory_log",
    "RedactedContext",
    "attach_prompt_provenance",
    "attach_prompt_provenance_to_run_result",
    "build_prompt_provenance",
    "SessionManager",
    "SessionState",
    "ToolAllowlistDecision",
    "ToolAllowlistMiddleware",
    "ToolPolicyError",
    "TaskTreeNode",
    "EvaluatorOptimizerResult",
    "EvaluatorOptimizerStep",
    "EvaluatorOptimizerWorkflowRunner",
    "OrchestratorWorkerTask",
    "OrchestratorWorkerWorkflowRunner",
    "ParallelAggregateResult",
    "ParallelWorkflowRunner",
    "ParallelWorkflowTask",
    "RefineLoopGuardDecision",
    "SequentialWorkflowRunner",
    "SequentialWorkflowStep",
    "RoutingWorkflowBranch",
    "RoutingWorkflowRunner",
    "WorkerGroupResult",
    "VALID_TASK_TRANSITIONS",
    "get_default_agent_registry",
    "get_default_permission_service",
    "intent_router_agent",
    "enforce_refine_loop_limit",
    "WorkflowMemoryBinding",
    "WorkflowMemoryBindings",
]
