"""Workflow and control-plane state definitions."""

from __future__ import annotations

from enum import StrEnum


class WorkflowState(StrEnum):
    CREATED = "CREATED"
    REASONING = "REASONING"
    PLANNING = "PLANNING"
    ACTING = "ACTING"
    OBSERVING = "OBSERVING"
    EVALUATING = "EVALUATING"
    REFINING = "REFINING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    BLOCKED_BY_RISK = "BLOCKED_BY_RISK"
    BLOCKED_BY_POLICY = "BLOCKED_BY_POLICY"
    TIMED_OUT = "TIMED_OUT"
    RECONCILING = "RECONCILING"


class ProposalState(StrEnum):
    DRAFT = "DRAFT"
    EVIDENCE_PENDING = "EVIDENCE_PENDING"
    READY_FOR_RISK = "READY_FOR_RISK"
    APPROVED = "APPROVED"
    APPROVED_WITH_LIMITS = "APPROVED_WITH_LIMITS"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    EXECUTION_PENDING = "EXECUTION_PENDING"
    SENT = "SENT"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    CLOSED = "CLOSED"


class IncidentState(StrEnum):
    DETECTED = "DETECTED"
    TRIAGED = "TRIAGED"
    ACTIVE = "ACTIVE"
    CONTAINED = "CONTAINED"
    RESOLVED = "RESOLVED"
    POSTMORTEM_PENDING = "POSTMORTEM_PENDING"
    CLOSED = "CLOSED"


class KillSwitchState(StrEnum):
    ARMED = "ARMED"
    SOFT_TRIGGERED = "SOFT_TRIGGERED"
    HARD_TRIGGERED = "HARD_TRIGGERED"
    RECOVERY_PENDING = "RECOVERY_PENDING"
    RECOVERY_APPROVED = "RECOVERY_APPROVED"
