"""Database migration scaffolding for the agentic backend."""

from .migrations.runner import (
    MigrationRecord,
    apply_pending_migrations,
    discover_migrations,
    ensure_migration_table,
)
from .repositories import (
    ApprovalRecord,
    ApprovalVoteRecord,
    ExecutionIntentRecord,
    ExecutionReceiptRecord,
    ExecutionRepository,
    ExecutionSendAttemptRecord,
    GovernanceRepository,
    PolicyRecord,
    ProposalRecord,
    ProposalRepository,
    ReconciliationRunRecord,
    RiskAssessmentRequestRecord,
    RiskConstraintRecord,
    RiskDecisionRecord,
    RiskRepository,
    StrategyRecord,
    WorkflowRecord,
    WorkflowRepository,
)

__all__ = [
    "MigrationRecord",
    "apply_pending_migrations",
    "discover_migrations",
    "ensure_migration_table",
    "ApprovalRecord",
    "ApprovalVoteRecord",
    "ExecutionIntentRecord",
    "ExecutionReceiptRecord",
    "ExecutionRepository",
    "ExecutionSendAttemptRecord",
    "GovernanceRepository",
    "PolicyRecord",
    "ProposalRecord",
    "ProposalRepository",
    "ReconciliationRunRecord",
    "RiskAssessmentRequestRecord",
    "RiskConstraintRecord",
    "RiskDecisionRecord",
    "RiskRepository",
    "StrategyRecord",
    "WorkflowRecord",
    "WorkflowRepository",
]
