"""Database migration scaffolding for the agentic backend."""

from .partitions import PartitionTarget, resolve_partition_target
from .migrations.runner import (
    MigrationRecord,
    apply_pending_migrations,
    discover_migrations,
    ensure_migration_table,
)
from .repositories import (
    ApprovalRecord,
    ApprovalVoteRecord,
    EvidenceBundleRecord,
    ExecutionIntentRecord,
    ExecutionReceiptRecord,
    ExecutionRepository,
    ExecutionSendAttemptRecord,
    GovernanceRepository,
    IncidentRecord,
    KillSwitchEventRecord,
    LegalHoldRecord,
    PolicyRecord,
    ProposalRecord,
    ProposalRepository,
    ReplayBundleRecord,
    ResearchAuditRepository,
    ReconciliationRunRecord,
    RiskAssessmentRequestRecord,
    RiskConstraintRecord,
    RiskDecisionRecord,
    RiskRepository,
    StrategyPromotionRecord,
    StrategyRecord,
    TrajectoryLogRecord,
    WorkflowRecord,
    WorkflowRepository,
)

__all__ = [
    "MigrationRecord",
    "PartitionTarget",
    "apply_pending_migrations",
    "discover_migrations",
    "ensure_migration_table",
    "resolve_partition_target",
    "ApprovalRecord",
    "ApprovalVoteRecord",
    "EvidenceBundleRecord",
    "ExecutionIntentRecord",
    "ExecutionReceiptRecord",
    "ExecutionRepository",
    "ExecutionSendAttemptRecord",
    "GovernanceRepository",
    "IncidentRecord",
    "KillSwitchEventRecord",
    "LegalHoldRecord",
    "PolicyRecord",
    "ProposalRecord",
    "ProposalRepository",
    "ReplayBundleRecord",
    "ResearchAuditRepository",
    "ReconciliationRunRecord",
    "RiskAssessmentRequestRecord",
    "RiskConstraintRecord",
    "RiskDecisionRecord",
    "RiskRepository",
    "StrategyPromotionRecord",
    "StrategyRecord",
    "TrajectoryLogRecord",
    "WorkflowRecord",
    "WorkflowRepository",
]
