"""Canonical risk service domain for safety checks and portfolio risk engines."""

from __future__ import annotations

_EXPORT_MODULES = {
    "ComposedRiskDecision": "governance.decisions",
    "PackedRiskDecisionArtifacts": "governance.decisions",
    "RiskDecisionEnvelopeContext": "governance.decisions",
    "RiskDecisionProvenance": "governance.decisions",
    "compose_risk_decision": "governance.decisions",
    "pack_risk_decision_rationale_and_provenance": "governance.decisions",
    "CorrelationConcentration": "calculations.correlation",
    "CorrelationPair": "calculations.correlation",
    "calculate_correlation_concentration": "calculations.correlation",
    "correlation_failures": "calculations.correlation",
    "correlation_impact": "calculations.correlation",
    "ConcentrationResult": "calculations.exposure",
    "ExposureSummary": "calculations.exposure",
    "PositionExposure": "calculations.exposure",
    "calculate_currency_concentration": "calculations.exposure",
    "calculate_exposure_summary": "calculations.exposure",
    "calculate_strategy_family_concentration": "calculations.exposure",
    "calculate_symbol_concentration": "calculations.exposure",
    "concentration_failures": "calculations.exposure",
    "exposure_snapshot": "calculations.exposure",
    "proposed_exposure_impact": "calculations.exposure",
    "DrawdownState": "calculations.margin",
    "MarginUtilization": "calculations.margin",
    "VolatilityAdjustedSizing": "calculations.margin",
    "calculate_drawdown_state": "calculations.margin",
    "calculate_margin_utilization": "calculations.margin",
    "calculate_volatility_adjusted_size": "calculations.margin",
    "margin_failures": "calculations.margin",
    "margin_impact": "calculations.margin",
    "RiskApprovalToken": "domain.contracts",
    "RiskAssessmentRequest": "domain.proposal",
    "RiskDecision": "domain.decision",
    "RiskGovernorDecision": "domain.contracts",
    "RiskMemo": "domain.contracts",
    "RiskProposal": "domain.contracts",
    "RiskGovernor": "governance.governor",
    "DEFAULT_RISK_THRESHOLDS": "governance.governor",
    "create_approval_token": "governance.approval_tokens",
    "validate_approval_token": "governance.approval_tokens",
    "RiskDecisionPersistenceService": "storage.decision_store",
    "RiskRequestAssemblyContext": "workflows.request_assembler",
    "assemble_risk_assessment_request": "workflows.request_assembler",
    "RestrictionEvaluation": "policy.restrictions",
    "evaluate_compliance_profile_compatibility": "policy.restrictions",
    "evaluate_operating_mode_compatibility": "policy.restrictions",
    "evaluate_regime_restriction": "policy.restrictions",
    "evaluate_session_restrictions": "policy.restrictions",
    "evaluate_spread_slippage_precheck": "policy.restrictions",
    "ACCOUNT_SNAPSHOT_TTL_POLICY": "domain.snapshot",
    "AccountSnapshot": "domain.snapshot",
    "AccountSnapshotType": "domain.snapshot",
    "MARKET_SNAPSHOT_TTL_POLICY": "domain.snapshot",
    "MarketSnapshot": "domain.snapshot",
    "MarketSnapshotType": "domain.snapshot",
    "PORTFOLIO_SNAPSHOT_TTL_POLICY": "domain.snapshot",
    "PortfolioSnapshot": "domain.snapshot",
    "PortfolioSnapshotType": "domain.snapshot",
    "RiskDecisionValidity": "governance.validity",
    "enforce_risk_decision_expiry": "governance.validity",
    "invalidate_for_material_proposal_change": "governance.validity",
    "GovernanceEngine": "core",
    "GovernanceReport": "core",
    "PortfolioRiskEngine": "core",
    "PortfolioStateBuilder": "api.public",
    "PortfolioStateEngine": "core",
    "RecommendationEngine": "core",
    "RiskScorecardEngine": "core",
    "RiskSnapshotBuilder": "api.public",
    "RiskSnapshotEngine": "core",
    "TimelinePoint": "core",
    "TimelineReconstructor": "core",
    "BudgetUtilization": "limits",
    "CircuitBreakerState": "limits",
    "CorrelationPreference": "limits",
    "GovernanceState": "limits",
    "LimitEvent": "limits",
    "OverrideRecord": "limits",
    "PolicyDecision": "limits",
    "PolicyEngine": "limits",
    "RiskLimits": "limits",
    "RiskPolicy": "limits",
    "AccountState": "domain",
    "MarketState": "domain",
    "PortfolioState": "domain",
    "PositionState": "domain",
    "SymbolState": "domain",
    "PositionSizer": "calculations.position_sizing",
    "estimate_kelly_parameters": "calculations.position_sizing",
    "validate_position_size": "calculations.position_sizing",
    "AllocationPlanner": "optimization",
    "AllocationOptimizer": "optimization",
    "CapitalEfficiencyRanker": "optimization",
    "HedgeOptimizer": "optimization",
    "MarginalRiskEvaluator": "optimization",
    "RecommendationAction": "optimization",
    "RecommendationBatch": "optimization",
    "RecommendationResult": "optimization",
    "RecommendationScore": "optimization",
    "RebalanceSuggestionEngine": "optimization",
    "CrisisRegimeDetector": "regimes",
    "LiquidityRegimeDetector": "regimes",
    "MarketRegimeDetector": "regimes",
    "RegimeEngine": "regimes",
    "RegimeReport": "regimes",
    "RegimeSignal": "regimes",
    "RegimeState": "regimes",
    "RegimeTransition": "regimes",
    "RiskRegimeDetector": "regimes",
    "VolatilityRegimeDetector": "regimes",
    "build_regime_transition": "regimes",
    "build_replay_report": "reports",
    "build_risk_snapshot_report": "reports",
    "RiskReportBuilder": "api.public",
    "build_scenario_report": "reports",
    "render_replay_report_markdown": "reports",
    "render_risk_report_markdown": "reports",
    "render_scenario_report_markdown": "reports",
    "save_json_report": "reports",
    "save_markdown_report": "reports",
    "ScenarioRegistry": "scenarios",
    "ScenarioResult": "scenarios",
    "StressScenario": "scenarios",
    "build_default_scenario_registry": "scenarios",
    "evaluate_scenarios": "scenarios",
    "CockpitStatePayload": "replay",
    "HypotheticalOrderAction": "replay",
    "ReplayClock": "replay",
    "ReplayEngine": "replay",
    "ReplayFrame": "replay",
    "ReplayRun": "replay",
    "WhatIfComparison": "replay",
    "WhatIfEngine": "replay",
    "apply_hypothetical_actions": "replay",
    "build_cockpit_state": "replay",
}

__all__ = list(_EXPORT_MODULES)


def __getattr__(name: str):
    """Load risk symbols lazily so callers do not import the full risk graph."""
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    from importlib import import_module

    module = import_module(f"{__name__}.{module_name}")
    value = getattr(module, name)
    globals()[name] = value
    return value
