"""Canonical risk service domain for safety checks and portfolio risk engines."""

from __future__ import annotations

_EXPORT_MODULES = {
    "ComposedRiskDecision": "decisions",
    "PackedRiskDecisionArtifacts": "decisions",
    "RiskDecisionEnvelopeContext": "decisions",
    "RiskDecisionProvenance": "decisions",
    "compose_risk_decision": "decisions",
    "pack_risk_decision_rationale_and_provenance": "decisions",
    "CorrelationConcentration": "correlation",
    "CorrelationPair": "correlation",
    "calculate_correlation_concentration": "correlation",
    "correlation_failures": "correlation",
    "correlation_impact": "correlation",
    "ConcentrationResult": "exposure",
    "ExposureSummary": "exposure",
    "PositionExposure": "exposure",
    "calculate_currency_concentration": "exposure",
    "calculate_exposure_summary": "exposure",
    "calculate_strategy_family_concentration": "exposure",
    "calculate_symbol_concentration": "exposure",
    "concentration_failures": "exposure",
    "exposure_snapshot": "exposure",
    "proposed_exposure_impact": "exposure",
    "DrawdownState": "margin",
    "MarginUtilization": "margin",
    "VolatilityAdjustedSizing": "margin",
    "calculate_drawdown_state": "margin",
    "calculate_margin_utilization": "margin",
    "calculate_volatility_adjusted_size": "margin",
    "margin_failures": "margin",
    "margin_impact": "margin",
    "RiskApprovalToken": "contracts",
    "RiskGovernorDecision": "contracts",
    "RiskMemo": "contracts",
    "RiskProposal": "contracts",
    "RiskGovernor": "governor",
    "DEFAULT_RISK_THRESHOLDS": "governor",
    "create_approval_token": "approval_tokens",
    "validate_approval_token": "approval_tokens",
    "RiskDecisionPersistenceService": "persistence",
    "RiskRequestAssemblyContext": "request_assembler",
    "assemble_risk_assessment_request": "request_assembler",
    "RestrictionEvaluation": "restrictions",
    "evaluate_compliance_profile_compatibility": "restrictions",
    "evaluate_operating_mode_compatibility": "restrictions",
    "evaluate_regime_restriction": "restrictions",
    "evaluate_session_restrictions": "restrictions",
    "evaluate_spread_slippage_precheck": "restrictions",
    "ACCOUNT_SNAPSHOT_TTL_POLICY": "snapshots",
    "AccountSnapshot": "snapshots",
    "AccountSnapshotType": "snapshots",
    "MARKET_SNAPSHOT_TTL_POLICY": "snapshots",
    "MarketSnapshot": "snapshots",
    "MarketSnapshotType": "snapshots",
    "PORTFOLIO_SNAPSHOT_TTL_POLICY": "snapshots",
    "PortfolioSnapshot": "snapshots",
    "PortfolioSnapshotType": "snapshots",
    "RiskDecisionValidity": "validity",
    "enforce_risk_decision_expiry": "validity",
    "invalidate_for_material_proposal_change": "validity",
    "GovernanceEngine": "core",
    "GovernanceReport": "core",
    "PortfolioRiskEngine": "core",
    "PortfolioStateEngine": "core",
    "RecommendationEngine": "core",
    "RiskScorecardEngine": "core",
    "RiskSnapshotEngine": "core",
    "TimelinePoint": "core",
    "TimelineReconstructor": "core",
    "BudgetUtilization": "limits",
    "CircuitBreakerState": "limits",
    "CorrelationPreference": "limits",
    "GovernanceState": "limits",
    "LimitEvent": "limits",
    "OverrideRecord": "limits",
    "PolicyDecision": "limits",
    "PolicyEngine": "limits",
    "RiskLimits": "limits",
    "RiskPolicy": "limits",
    "AccountState": "models",
    "MarketState": "models",
    "PortfolioState": "models",
    "PositionState": "models",
    "SymbolState": "models",
    "PositionSizer": "position_sizing",
    "estimate_kelly_parameters": "position_sizing",
    "validate_position_size": "position_sizing",
    "AllocationPlanner": "optimization",
    "AllocationOptimizer": "optimization",
    "CapitalEfficiencyRanker": "optimization",
    "HedgeOptimizer": "optimization",
    "MarginalRiskEvaluator": "optimization",
    "RecommendationAction": "optimization",
    "RecommendationBatch": "optimization",
    "RecommendationResult": "optimization",
    "RecommendationScore": "optimization",
    "RebalanceSuggestionEngine": "optimization",
    "CrisisRegimeDetector": "regimes",
    "LiquidityRegimeDetector": "regimes",
    "MarketRegimeDetector": "regimes",
    "RegimeEngine": "regimes",
    "RegimeReport": "regimes",
    "RegimeSignal": "regimes",
    "RegimeState": "regimes",
    "RegimeTransition": "regimes",
    "RiskRegimeDetector": "regimes",
    "VolatilityRegimeDetector": "regimes",
    "build_regime_transition": "regimes",
    "build_replay_report": "reports",
    "build_risk_snapshot_report": "reports",
    "build_scenario_report": "reports",
    "render_replay_report_markdown": "reports",
    "render_risk_report_markdown": "reports",
    "render_scenario_report_markdown": "reports",
    "save_json_report": "reports",
    "save_markdown_report": "reports",
    "ScenarioRegistry": "scenarios",
    "ScenarioResult": "scenarios",
    "StressScenario": "scenarios",
    "build_default_scenario_registry": "scenarios",
    "evaluate_scenarios": "scenarios",
    "CockpitStatePayload": "simulation",
    "HypotheticalOrderAction": "simulation",
    "ReplayClock": "simulation",
    "ReplayEngine": "simulation",
    "ReplayFrame": "simulation",
    "ReplayRun": "simulation",
    "WhatIfComparison": "simulation",
    "WhatIfEngine": "simulation",
    "apply_hypothetical_actions": "simulation",
    "build_cockpit_state": "simulation",
}

__all__ = list(_EXPORT_MODULES)


def __getattr__(name: str):
    """Load risk symbols lazily so callers do not import the full risk graph."""
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    from importlib import import_module

    module = import_module(f"{__name__}.{module_name}")
    value = getattr(module, name)
    globals()[name] = value
    return value
