"""Market data MCP boundary package."""

from backend.services.market_data.dukascopy_instruments import get_instrument

from .dukascopy import (
    INTERVAL_DAY_1,
    INTERVAL_HOUR_1,
    INTERVAL_HOUR_4,
    INTERVAL_MIN_1,
    INTERVAL_MIN_5,
    INTERVAL_MIN_10,
    INTERVAL_MIN_15,
    INTERVAL_MIN_30,
    INTERVAL_MONTH_1,
    INTERVAL_SEC_1,
    INTERVAL_SEC_10,
    INTERVAL_SEC_30,
    INTERVAL_TICK,
    INTERVAL_WEEK_1,
    OFFER_SIDE_ASK,
    OFFER_SIDE_BID,
    TIME_UNIT_DAY,
    TIME_UNIT_HOUR,
    TIME_UNIT_MIN,
    TIME_UNIT_MONTH,
    TIME_UNIT_SEC,
    TIME_UNIT_TICK,
    TIME_UNIT_WEEK,
    fetch,
    live_fetch,
)
from .server import MarketDataMCPServer, create_market_data_mcp_server
from .tools import (
    MARKET_DATA_TOOL_SPECS,
    DukascopyGateway,
    DukascopyMarketDataTools,
    HistoricalMarketDataGateway,
)

__all__ = [
    "INTERVAL_DAY_1",
    "INTERVAL_HOUR_1",
    "INTERVAL_HOUR_4",
    "INTERVAL_MIN_1",
    "INTERVAL_MIN_5",
    "INTERVAL_MIN_10",
    "INTERVAL_MIN_15",
    "INTERVAL_MIN_30",
    "INTERVAL_MONTH_1",
    "INTERVAL_SEC_1",
    "INTERVAL_SEC_10",
    "INTERVAL_SEC_30",
    "INTERVAL_TICK",
    "INTERVAL_WEEK_1",
    "OFFER_SIDE_ASK",
    "OFFER_SIDE_BID",
    "TIME_UNIT_DAY",
    "TIME_UNIT_HOUR",
    "TIME_UNIT_MIN",
    "TIME_UNIT_MONTH",
    "TIME_UNIT_SEC",
    "TIME_UNIT_TICK",
    "TIME_UNIT_WEEK",
    "fetch",
    "live_fetch",
    "get_instrument",
    "DukascopyGateway",
    "DukascopyMarketDataTools",
    "HistoricalMarketDataGateway",
    "MARKET_DATA_TOOL_SPECS",
    "MarketDataMCPServer",
    "create_market_data_mcp_server",
]
