"""Risk Governor module."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Literal, Optional, Tuple

import numpy as np
import pandas as pd
from scipy import stats

from apps.logger import logger

from .regime import RegimeState
from .risk_limits import RiskLimits

Decision = Literal["ACCEPT", "REJECT"]


@dataclass(frozen=True)
class RiskReport:
    """Report generated by Risk Governor decision."""

    decision: Decision
    reason: str

    current_var: float
    new_var: float
    delta_var: float

    current_es: float
    new_es: float
    delta_es: float

    current_margin_used: Optional[float] = None
    new_margin_used: Optional[float] = None

    rc_map_new: Optional[Dict[str, float]] = None
    rc_violations: Optional[List[str]] = None

    cluster_violations: Optional[List[str]] = None


class RiskGovernor:
    """Portfolio risk gatekeeper (hard constraints)."""

    def __init__(
        self,
        mt5_client,
        limits: RiskLimits,
        timeframe: str = "D1",
        start_pos: int = 0,
        end_pos: int = 500,
    ):
        """Initialize Risk Governor."""
        self.mt5_client = mt5_client
        self.limits = limits
        self.timeframe = timeframe
        self.start_pos = start_pos
        self.end_pos = end_pos

    # ----------------------------- public API -----------------------------

    def evaluate_add_position(
        self,
        current_positions: Dict[str, float],
        candidate_symbol: str,
        candidate_lots: float,
        symbol_to_cluster: Optional[Dict[str, str]] = None,
        regime: Optional[RegimeState] = None,
    ) -> RiskReport:
        """Evaluate adding a position against risk limits."""
        new_positions = dict(current_positions)
        new_positions[candidate_symbol] = (
            new_positions.get(candidate_symbol, 0.0) + candidate_lots
        )
        if abs(new_positions[candidate_symbol]) < 1e-12:
            del new_positions[candidate_symbol]

        # If action reduces exposure count, typically accept (can be made stricter)
        if len(new_positions) < len(current_positions):
            return self._report_decision(
                decision="ACCEPT",
                reason="Candidate reduces or nets existing exposure.",
                current_positions=current_positions,
                new_positions=new_positions,
                symbol_to_cluster=symbol_to_cluster,
                regime=regime,
            )

        return self._decide_with_limits(
            current_positions, new_positions, symbol_to_cluster, regime
        )

    def effective_limits(self, regime: Optional[RegimeState]) -> RiskLimits:
        """Tighten limits in STRESS regime."""
        L = self.limits
        if regime is None or regime.name == "NORMAL":
            return L

        return RiskLimits(
            var_cap_frac=min(L.var_cap_frac, 0.07),
            es_cap_frac=min(L.es_cap_frac, 0.10),
            delta_var_cap_frac=min(L.delta_var_cap_frac, 0.015),
            delta_es_cap_frac=min(L.delta_es_cap_frac, 0.02),
            max_margin_used_frac=min(L.max_margin_used_frac, 0.35),
            min_pair_corr=max(L.min_pair_corr, 0.35),
            stressed_corr_floor=max(L.stressed_corr_floor, 0.75),
            use_stressed_corr=True,
            confidence_level=L.confidence_level,
            time_horizon_days=L.time_horizon_days,
            vol_lookback=L.vol_lookback,
            corr_lookback=L.corr_lookback,
            max_single_rc_frac=min(L.max_single_rc_frac, 0.12),
            rc_rebalance_tolerance=L.rc_rebalance_tolerance,
            cluster_var_caps=L.cluster_var_caps,
            cluster_es_caps=L.cluster_es_caps,
        )

    # --------------------------- decision policy --------------------------

    def _decide_with_limits(
        self,
        current_positions: Dict[str, float],
        new_positions: Dict[str, float],
        symbol_to_cluster: Optional[Dict[str, str]],
        regime: Optional[RegimeState],
    ) -> RiskReport:
        eff = self.effective_limits(regime)
        equity = float(self.mt5_client.get_account_equity())

        cur_var, cur_es, cur_margin, _ = self._compute_portfolio_risk(
            current_positions, equity, eff
        )
        new_var, new_es, new_margin, rc_map_new = self._compute_portfolio_risk(
            new_positions, equity, eff
        )

        delta_var = new_var - cur_var
        delta_es = new_es - cur_es

        # Margin cap (optional)
        if (cur_margin is not None) and (new_margin is not None):
            margin_cap = eff.max_margin_used_frac * equity
            if new_margin > margin_cap:
                return RiskReport(
                    decision="REJECT",
                    reason=f"Margin cap exceeded: new_margin={new_margin:,.2f} > cap={margin_cap:,.2f}",
                    current_var=cur_var,
                    new_var=new_var,
                    delta_var=delta_var,
                    current_es=cur_es,
                    new_es=new_es,
                    delta_es=delta_es,
                    current_margin_used=cur_margin,
                    new_margin_used=new_margin,
                    rc_map_new=rc_map_new,
                    rc_violations=None,
                    cluster_violations=None,
                )

        # Absolute caps
        var_cap = eff.var_cap_frac * equity
        es_cap = eff.es_cap_frac * equity
        if new_var > var_cap:
            return RiskReport(
                decision="REJECT",
                reason=f"Portfolio VaR cap exceeded: new_var={new_var:,.2f} > cap={var_cap:,.2f}",
                current_var=cur_var,
                new_var=new_var,
                delta_var=delta_var,
                current_es=cur_es,
                new_es=new_es,
                delta_es=delta_es,
                current_margin_used=cur_margin,
                new_margin_used=new_margin,
                rc_map_new=rc_map_new,
                rc_violations=None,
                cluster_violations=None,
            )
        if new_es > es_cap:
            return RiskReport(
                decision="REJECT",
                reason=f"Portfolio ES cap exceeded: new_es={new_es:,.2f} > cap={es_cap:,.2f}",
                current_var=cur_var,
                new_var=new_var,
                delta_var=delta_var,
                current_es=cur_es,
                new_es=new_es,
                delta_es=delta_es,
                current_margin_used=cur_margin,
                new_margin_used=new_margin,
                rc_map_new=rc_map_new,
                rc_violations=None,
                cluster_violations=None,
            )

        # Incremental caps
        dvar_cap = eff.delta_var_cap_frac * equity
        des_cap = eff.delta_es_cap_frac * equity
        if delta_var > dvar_cap:
            return RiskReport(
                decision="REJECT",
                reason=f"Delta VaR cap exceeded: delta_var={delta_var:,.2f} > cap={dvar_cap:,.2f}",
                current_var=cur_var,
                new_var=new_var,
                delta_var=delta_var,
                current_es=cur_es,
                new_es=new_es,
                delta_es=delta_es,
                current_margin_used=cur_margin,
                new_margin_used=new_margin,
                rc_map_new=rc_map_new,
                rc_violations=None,
                cluster_violations=None,
            )
        if delta_es > des_cap:
            return RiskReport(
                decision="REJECT",
                reason=f"Delta ES cap exceeded: delta_es={delta_es:,.2f} > cap={des_cap:,.2f}",
                current_var=cur_var,
                new_var=new_var,
                delta_var=delta_var,
                current_es=cur_es,
                new_es=new_es,
                delta_es=delta_es,
                current_margin_used=cur_margin,
                new_margin_used=new_margin,
                rc_map_new=rc_map_new,
                rc_violations=None,
                cluster_violations=None,
            )

        # Risk contribution cap
        # Allow first trade to pass RC cap; single-position portfolios are 100% RC by definition.
        rc_viol = []
        if len(new_positions) > 1:
            rc_viol = self._rc_violations(rc_map_new or {}, eff.max_single_rc_frac)
        if rc_viol:
            return RiskReport(
                decision="REJECT",
                reason=f"Risk contribution cap exceeded by {rc_viol}",
                current_var=cur_var,
                new_var=new_var,
                delta_var=delta_var,
                current_es=cur_es,
                new_es=new_es,
                delta_es=delta_es,
                current_margin_used=cur_margin,
                new_margin_used=new_margin,
                rc_map_new=rc_map_new,
                rc_violations=rc_viol,
                cluster_violations=None,
            )

        # Cluster limits
        violations = self._check_cluster_caps(
            new_positions, equity, symbol_to_cluster, eff
        )
        if violations:
            return RiskReport(
                decision="REJECT",
                reason="Cluster cap exceeded.",
                current_var=cur_var,
                new_var=new_var,
                delta_var=delta_var,
                current_es=cur_es,
                new_es=new_es,
                delta_es=delta_es,
                current_margin_used=cur_margin,
                new_margin_used=new_margin,
                rc_map_new=rc_map_new,
                rc_violations=None,
                cluster_violations=violations,
            )

        return RiskReport(
            decision="ACCEPT",
            reason="All risk limits satisfied.",
            current_var=cur_var,
            new_var=new_var,
            delta_var=delta_var,
            current_es=cur_es,
            new_es=new_es,
            delta_es=delta_es,
            current_margin_used=cur_margin,
            new_margin_used=new_margin,
            rc_map_new=rc_map_new,
            rc_violations=None,
            cluster_violations=None,
        )

    def _report_decision(
        self,
        decision: Decision,
        reason: str,
        current_positions: Dict[str, float],
        new_positions: Dict[str, float],
        symbol_to_cluster: Optional[Dict[str, str]],
        regime: Optional[RegimeState],
    ) -> RiskReport:
        eff = self.effective_limits(regime)
        equity = float(self.mt5_client.get_account_equity())
        cur_var, cur_es, cur_margin, _ = self._compute_portfolio_risk(
            current_positions, equity, eff
        )
        new_var, new_es, new_margin, rc_map_new = self._compute_portfolio_risk(
            new_positions, equity, eff
        )
        return RiskReport(
            decision=decision,
            reason=reason,
            current_var=cur_var,
            new_var=new_var,
            delta_var=new_var - cur_var,
            current_es=cur_es,
            new_es=new_es,
            delta_es=new_es - cur_es,
            current_margin_used=cur_margin,
            new_margin_used=new_margin,
            rc_map_new=rc_map_new,
            rc_violations=self._rc_violations(rc_map_new or {}, eff.max_single_rc_frac)
            or None,
            cluster_violations=self._check_cluster_caps(
                new_positions, equity, symbol_to_cluster, eff
            )
            or None,
        )

    # ----------------------------- risk math ------------------------------

    def _compute_portfolio_risk(
        self,
        positions: Dict[str, float],
        equity: float,
        eff: RiskLimits,
    ) -> Tuple[float, float, Optional[float], Optional[Dict[str, float]]]:
        if not positions:
            return 0.0, 0.0, 0.0, {}

        symbols = list(positions.keys())
        data = self._get_data(symbols, exclude_current_bar=True)

        returns_df = self._build_returns_df(data, symbols)
        need = max(eff.vol_lookback, eff.corr_lookback)
        if returns_df.empty or returns_df.dropna().shape[0] < need:
            logger.warning(
                "RiskGovernor: insufficient returns data for VaR/ES (symbols=%s, rows=%s, need=%s)",
                symbols,
                int(returns_df.dropna().shape[0]) if not returns_df.empty else 0,
                need,
            )
            return (
                float("inf"),
                float("inf"),
                self._estimate_margin_used(positions),
                None,
            )

        cov = self._estimate_covariance(returns_df, symbols, eff)
        weights = self._build_weights_from_positions(positions, data, symbols)

        port_var = float(weights.T @ cov @ weights)
        port_std = float(np.sqrt(max(port_var, 0.0)))

        portfolio_value = self._portfolio_notional_value(positions, data, symbols)
        if portfolio_value <= 0 or port_std <= 0:
            logger.warning(
                "RiskGovernor: invalid portfolio inputs for VaR/ES (portfolio_value=%s, port_std=%s, symbols=%s)",
                portfolio_value,
                port_std,
                symbols,
            )
            return (
                float("inf"),
                float("inf"),
                self._estimate_margin_used(positions),
                None,
            )

        z = stats.norm.ppf(eff.confidence_level)
        t = np.sqrt(eff.time_horizon_days)

        var_dollar = z * port_std * t * portfolio_value

        alpha = eff.confidence_level
        phi = stats.norm.pdf(z)
        es_dollar = (phi / (1.0 - alpha)) * port_std * t * portfolio_value

        rc_pct = self._compute_risk_contributions_pct(weights, cov, symbols)

        margin_used = self._estimate_margin_used(positions)
        return float(var_dollar), float(es_dollar), margin_used, rc_pct

    def _estimate_covariance(
        self, returns_df: pd.DataFrame, symbols: List[str], eff: RiskLimits
    ) -> np.ndarray:
        r = returns_df[symbols].dropna()
        vol = r.rolling(eff.vol_lookback).std().iloc[-1].values
        vol = np.nan_to_num(vol, nan=0.0)

        rolling_corr = r.rolling(eff.corr_lookback).corr()
        last_ts = rolling_corr.index.get_level_values(0).unique()[-1]
        corr_mat = (
            rolling_corr.loc[last_ts].reindex(index=symbols, columns=symbols).values
        )
        corr_mat = np.nan_to_num(corr_mat, nan=0.0)
        np.fill_diagonal(corr_mat, 1.0)

        corr_mat = self._apply_corr_floors(corr_mat, eff)

        return np.outer(vol, vol) * corr_mat

    def _apply_corr_floors(self, corr_mat: np.ndarray, eff: RiskLimits) -> np.ndarray:
        n = corr_mat.shape[0]
        out = corr_mat.copy()

        floor = eff.stressed_corr_floor if eff.use_stressed_corr else eff.min_pair_corr
        floor = max(eff.min_pair_corr, floor)

        for i in range(n):
            for j in range(n):
                if i == j:
                    continue
                out[i, j] = max(out[i, j], floor)

        out = np.clip(out, -1.0, 1.0)
        np.fill_diagonal(out, 1.0)
        return out

    def _build_weights_from_positions(
        self,
        positions: Dict[str, float],
        historical_data: Dict[str, pd.DataFrame],
        symbols: List[str],
    ) -> np.ndarray:
        notionals = []
        for s in symbols:
            notionals.append(
                abs(
                    self._symbol_notional_value(
                        s, float(positions.get(s, 0.0)), historical_data
                    )
                )
            )

        total = float(np.sum(notionals))
        if total <= 0:
            return np.zeros(len(symbols), dtype=float)
        return np.array([n / total for n in notionals], dtype=float)

    def _compute_risk_contributions_pct(
        self, weights: np.ndarray, cov: np.ndarray, symbols: List[str]
    ) -> Dict[str, float]:
        port_var = float(weights.T @ cov @ weights)
        if port_var <= 0:
            return dict.fromkeys(symbols, 0.0)

        mrc = cov @ weights
        rc = weights * mrc
        rc_pct = rc / port_var
        return {symbols[i]: float(rc_pct[i]) for i in range(len(symbols))}

    def _rc_violations(self, rc_pct: Dict[str, float], max_single: float) -> List[str]:
        return [s for s, v in rc_pct.items() if v > max_single]

    # Used by allocator for the "pro move"
    def _portfolio_correlation_map(
        self, weights: np.ndarray, cov: np.ndarray, symbols: List[str]
    ) -> Dict[str, float]:
        port_var = float(weights.T @ cov @ weights)
        if port_var <= 0:
            return dict.fromkeys(symbols, 0.0)

        port_std = float(np.sqrt(port_var))
        cov_w = cov @ weights

        corr_map: Dict[str, float] = {}
        for i, s in enumerate(symbols):
            sym_var = float(cov[i, i])
            if sym_var <= 0:
                corr_map[s] = 0.0
            else:
                corr_map[s] = float(cov_w[i] / (np.sqrt(sym_var) * port_std))
        return corr_map

    # ----------------------------- clusters ------------------------------

    def _check_cluster_caps(
        self,
        positions: Dict[str, float],
        equity: float,
        symbol_to_cluster: Optional[Dict[str, str]],
        eff: RiskLimits,
    ) -> List[str]:
        if not positions or not symbol_to_cluster:
            return []

        var_caps = eff.cluster_var_caps or {}
        es_caps = eff.cluster_es_caps or {}
        if not var_caps and not es_caps:
            return []

        clusters = self._group_positions_by_cluster(positions, symbol_to_cluster)

        violations: List[str] = []
        for ck, cpos in clusters.items():
            violations.extend(
                self._check_single_cluster_cap(ck, cpos, equity, eff, var_caps, es_caps)
            )
        return violations

    def _group_positions_by_cluster(
        self, positions: Dict[str, float], symbol_to_cluster: Dict[str, str]
    ) -> Dict[str, Dict[str, float]]:
        clusters: Dict[str, Dict[str, float]] = {}
        for sym, lots in positions.items():
            ck = symbol_to_cluster.get(sym)
            if not ck:
                continue
            clusters.setdefault(ck, {})[sym] = lots
        return clusters

    def _check_single_cluster_cap(
        self,
        cluster_key: str,
        positions: Dict[str, float],
        equity: float,
        eff: RiskLimits,
        var_caps: Dict[str, float],
        es_caps: Dict[str, float],
    ) -> List[str]:
        if cluster_key not in var_caps and cluster_key not in es_caps:
            return []

        c_var, c_es, _, _ = self._compute_portfolio_risk(positions, equity, eff)
        violations = []

        if cluster_key in var_caps:
            cap = var_caps[cluster_key] * equity
            if c_var > cap:
                violations.append(f"{cluster_key}: VaR {c_var:,.2f} > cap {cap:,.2f}")

        if cluster_key in es_caps:
            cap = es_caps[cluster_key] * equity
            if c_es > cap:
                violations.append(f"{cluster_key}: ES {c_es:,.2f} > cap {cap:,.2f}")

        return violations

    # ----------------------------- margin -------------------------------

    def _estimate_margin_used(self, positions: Dict[str, float]) -> Optional[float]:
        if not positions:
            return 0.0

        if not hasattr(self.mt5_client, "get_margin_required"):
            return None

        total = 0.0
        for sym, lots in positions.items():
            if lots == 0:
                continue
            m = self.mt5_client.get_margin_required(sym, lots)
            if m is None:
                return None
            total += abs(float(m))
        return float(total)

    # ----------------------------- data --------------------------------

    def _get_data(
        self, symbols: List[str], exclude_current_bar: bool = True
    ) -> Dict[str, pd.DataFrame]:
        all_data: Dict[str, pd.DataFrame] = {}
        for symbol in symbols:
            df = self.mt5_client.get_bars(
                symbol=symbol,
                timeframe=self.timeframe,
                count=self.end_pos - self.start_pos,
                start_pos=self.start_pos,
            )
            if df is None or df.empty or "close" not in df.columns:
                continue

            # MT5Client returns lowercase column names, rename for compatibility
            if "close" in df.columns and "Close" not in df.columns:
                df.rename(columns={"close": "Close"}, inplace=True)

            if exclude_current_bar and len(df) > 1:
                df = df.iloc[:-1]

            all_data[symbol] = df
        return all_data

    def _build_returns_df(
        self, data: Dict[str, pd.DataFrame], symbols: List[str]
    ) -> pd.DataFrame:
        cols = {}
        for s in symbols:
            df = data.get(s)
            if df is None or df.empty:
                continue
            px = df["Close"].astype(float)
            cols[s] = np.log(px / px.shift(1))
        if not cols:
            return pd.DataFrame()
        return pd.DataFrame(cols).dropna(how="all")

    # ----------------------- notional / exposure ------------------------

    def _portfolio_notional_value(
        self,
        positions: Dict[str, float],
        historical_data: Dict[str, pd.DataFrame],
        symbols: List[str],
    ) -> float:
        total = 0.0
        for s in symbols:
            total += abs(
                self._symbol_notional_value(
                    s, float(positions.get(s, 0.0)), historical_data
                )
            )
        return float(total)

    def _symbol_notional_value(
        self, symbol: str, lots: float, historical_data: Dict[str, pd.DataFrame]
    ) -> float:
        df = historical_data.get(symbol)
        if df is None or df.empty:
            logger.warning("RiskGovernor: missing historical data for %s", symbol)
            return 0.0
        price = float(df["Close"].iloc[-1])

        info = self.mt5_client.get_symbol_info(symbol)
        if info is None:
            logger.warning("RiskGovernor: missing symbol_info for %s", symbol)
            return 0.0

        contract_size = (
            float(info.get("trade_contract_size", 0.0))
            if isinstance(info, dict)
            else float(getattr(info, "trade_contract_size", 0.0))
        )
        if contract_size > 0:
            return lots * contract_size * price

        tick_value = (
            float(info.get("trade_tick_value", 0.0))
            if isinstance(info, dict)
            else float(getattr(info, "trade_tick_value", 0.0))
        )
        tick_size = (
            float(info.get("trade_tick_size", 0.0))
            if isinstance(info, dict)
            else float(getattr(info, "trade_tick_size", 0.0))
        )
        if tick_value > 0 and tick_size > 0:
            value_per_price_unit = tick_value / tick_size
            return lots * value_per_price_unit * price

        logger.warning(
            "RiskGovernor: no valid contract/tick values for %s (contract_size=%s, tick_value=%s, tick_size=%s)",
            symbol,
            contract_size,
            tick_value,
            tick_size,
        )
        return 0.0

    # ------------------------ RC rebalance helper ------------------------

    def propose_rc_rebalance(
        self,
        positions: Dict[str, float],
        target_rc_budget: Dict[str, float],
        max_iters: int = 10,
        step_frac: float = 0.10,
        regime: Optional[RegimeState] = None,
    ) -> Dict[str, float]:
        """Propose position adjustments to align with risk contribution budget."""
        if not positions or len(positions) < 2:
            return {}

        eff = self.effective_limits(regime)
        symbols = list(positions.keys())
        data = self._get_data(symbols, exclude_current_bar=True)
        returns_df = self._build_returns_df(data, symbols)
        need = max(eff.vol_lookback, eff.corr_lookback)
        if returns_df.empty or returns_df.dropna().shape[0] < need:
            return {}

        cov = self._estimate_covariance(returns_df, symbols, eff)

        tgt = {s: float(target_rc_budget.get(s, 0.0)) for s in symbols}
        ssum = sum(tgt.values())
        if ssum <= 0:
            tgt = {s: 1.0 / len(symbols) for s in symbols}
        else:
            tgt = {s: v / ssum for s, v in tgt.items()}

        pos_work = dict(positions)
        proposed = dict.fromkeys(symbols, 0.0)

        for _ in range(max_iters):
            w = self._build_weights_from_positions(pos_work, data, symbols)
            rc = self._compute_risk_contributions_pct(w, cov, symbols)
            dev = {s: rc.get(s, 0.0) - tgt.get(s, 0.0) for s in symbols}

            over_sym, over_amt = max(dev.items(), key=lambda x: x[1])
            under_sym, under_amt = min(dev.items(), key=lambda x: x[1])

            if (
                over_amt <= eff.rc_rebalance_tolerance
                and abs(under_amt) <= eff.rc_rebalance_tolerance
            ):
                break

            if over_amt > eff.rc_rebalance_tolerance:
                delta = -step_frac * pos_work[over_sym]
                pos_work[over_sym] += delta
                proposed[over_sym] += delta

            if under_amt < -eff.rc_rebalance_tolerance:
                base = pos_work.get(under_sym, 0.0)
                bump = step_frac * (abs(base) if abs(base) > 1e-6 else 0.1)
                pos_work[under_sym] += bump
                proposed[under_sym] += bump

        return {s: d for s, d in proposed.items() if abs(d) > 1e-8}
