"""HaruQuant Risk Engine package.

Portfolio-First Risk Governance for Algorithmic Trading.

This package provides institutional-grade risk management with:
- GovernanceEngine: Hard constraints (VaR, ES, margin, concentration)
- AllocationPlanner: Risk parity allocation planning
- RiskRegimeDetector / RegimeEngine: Market regime detection and state-aware risk context
- PositionSizer: Dynamic position sizing (multiple methods)
- RiskLimits: Configuration for risk parameters
"""

from backend.services.risk_engine.core import (
    GovernanceEngine,
    GovernanceReport,
    PortfolioRiskEngine,
    RiskScorecardEngine,
    PortfolioStateEngine,
    RecommendationEngine,
    RiskSnapshotEngine,
    TimelinePoint,
    TimelineReconstructor,
)
from backend.services.risk_engine.limits import (
    BudgetUtilization,
    CircuitBreakerState,
    CorrelationPreference,
    GovernanceState,
    LimitEvent,
    OverrideRecord,
    PolicyDecision,
    PolicyEngine,
    RiskLimits,
    RiskPolicy,
)
from backend.services.risk_engine.models import (
    AccountState,
    MarketState,
    PortfolioState,
    PositionState,
    SymbolState,
)
from backend.services.risk_engine.position_sizing import (
    PositionSizer,
    estimate_kelly_parameters,
    validate_position_size,
)
from backend.services.risk_engine.optimization import (
    AllocationPlanner,
    AllocationOptimizer,
    CapitalEfficiencyRanker,
    HedgeOptimizer,
    MarginalRiskEvaluator,
    RecommendationAction,
    RecommendationBatch,
    RecommendationResult,
    RecommendationScore,
    RebalanceSuggestionEngine,
)
from backend.services.risk_engine.regimes import (
    CrisisRegimeDetector,
    LiquidityRegimeDetector,
    MarketRegimeDetector,
    RegimeEngine,
    RegimeReport,
    RegimeSignal,
    RegimeState,
    RegimeTransition,
    RiskRegimeDetector,
    VolatilityRegimeDetector,
    build_regime_transition,
)
from backend.services.risk_engine.reports import (
    build_replay_report,
    build_risk_snapshot_report,
    build_scenario_report,
    render_replay_report_markdown,
    render_risk_report_markdown,
    render_scenario_report_markdown,
    save_json_report,
    save_markdown_report,
)
from backend.services.risk_engine.scenarios import (
    ScenarioRegistry,
    ScenarioResult,
    StressScenario,
    build_default_scenario_registry,
    evaluate_scenarios,
)
from backend.services.risk_engine.simulation import (
    CockpitStatePayload,
    HypotheticalOrderAction,
    ReplayClock,
    ReplayEngine,
    ReplayFrame,
    ReplayRun,
    WhatIfComparison,
    WhatIfEngine,
    apply_hypothetical_actions,
    build_cockpit_state,
)

__all__ = [
    "PolicyEngine",
    "PolicyDecision",
    "LimitEvent",
    "GovernanceState",
    "OverrideRecord",
    "BudgetUtilization",
    "CircuitBreakerState",
    "GovernanceEngine",
    "GovernanceReport",
    "PortfolioRiskEngine",
    "AllocationPlanner",
    "PortfolioStateEngine",
    "RecommendationEngine",
    "RiskScorecardEngine",
    "RiskSnapshotEngine",
    "RegimeEngine",
    "RegimeReport",
    "RiskRegimeDetector",
    "RegimeState",
    "RegimeSignal",
    "RegimeTransition",
    "CrisisRegimeDetector",
    "MarketRegimeDetector",
    "VolatilityRegimeDetector",
    "LiquidityRegimeDetector",
    "build_regime_transition",
    "build_risk_snapshot_report",
    "build_scenario_report",
    "build_replay_report",
    "render_risk_report_markdown",
    "render_scenario_report_markdown",
    "render_replay_report_markdown",
    "save_json_report",
    "save_markdown_report",
    "PositionSizer",
    "RecommendationAction",
    "RecommendationBatch",
    "RecommendationResult",
    "RecommendationScore",
    "MarginalRiskEvaluator",
    "RebalanceSuggestionEngine",
    "CapitalEfficiencyRanker",
    "AllocationOptimizer",
    "HedgeOptimizer",
    "RiskPolicy",
    "RiskLimits",
    "CorrelationPreference",
    "AccountState",
    "PositionState",
    "SymbolState",
    "MarketState",
    "PortfolioState",
    "TimelinePoint",
    "TimelineReconstructor",
    "ReplayClock",
    "ReplayFrame",
    "ReplayRun",
    "ReplayEngine",
    "HypotheticalOrderAction",
    "WhatIfComparison",
    "WhatIfEngine",
    "CockpitStatePayload",
    "apply_hypothetical_actions",
    "build_cockpit_state",
    "ScenarioRegistry",
    "ScenarioResult",
    "StressScenario",
    "build_default_scenario_registry",
    "evaluate_scenarios",
    "validate_position_size",
    "estimate_kelly_parameters",
]
